[project]
name = "ipinfo-webhook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=6.1.1",
    "requests>=2.32.3",
]
